AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 4.0
  UseCache: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Lint/Debugger:
  Enabled: false
Metrics:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
