services:
  db:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    container_name: bbs-db
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 256M
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:?}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_USER: ${MYSQL_USER:?}
    healthcheck:
      test:
        - CMD-SHELL
        - MYSQL_PWD=${MYSQL_PASSWORD:?} mysql --host=bbs-db --port=3306 --database=${MYSQL_DATABASE:?} --user=${MYSQL_USER:?} --silent --execute="SELECT 1" &>/dev/null
      timeout: 10s
      interval: 10s
      retries: 5
      start_period: 0s
    image: ${MYSQL_IMAGE:?}
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
        volume: {}
  web:
    container_name: bbs-web
    depends_on:
      db:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          cpus: 0.3
          memory: 256M
        reservations:
          cpus: 0.1
          memory: 128M
    environment:
      DB_DATABASE: ${MYSQL_DATABASE:?}
      DB_HOST: bbs-db
      DB_PASSWORD: ${MYSQL_PASSWORD:?}
      DB_PORT: "3306"
      DB_USER: ${MYSQL_USER:?}
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f -L -o /dev/null -s -x "" http://localhost:4567/ || exit 1
      timeout: 10s
      interval: 10s
      retries: 5
      start_period: 0s
    image: ghcr.io/shakiyam/bbs
    logging:
      driver: journald
      options:
        tag: '{{.Name}}'
    networks:
      default: null
    ports:
      - mode: ingress
        target: 4567
        published: "4567"
        protocol: tcp
    read_only: true
    restart: unless-stopped
    tmpfs:
      - /tmp
networks:
  default:
    name: bbs-default
volumes:
  db-data:
    name: bbs-db-data
