services:
  db:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    container_name: bbs-db
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 256M
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:?}
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
      MYSQL_USER: ${MYSQL_USER:?}
    healthcheck:
      test:
        - CMD
        - /usr/local/bin/healthcheck.sh
      timeout: 10s
      interval: 10s
      retries: 5
      start_period: 0s
    image: ${MYSQL_IMAGE:?}
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"
    networks:
      default: null
    restart: unless-stopped
    secrets:
      - mysql_password
      - mysql_root_password
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
        volume: {}
      - type: bind
        source: ./db/healthcheck.sh
        target: /usr/local/bin/healthcheck.sh
        read_only: true
      - type: bind
        source: ./db/create_user.sh
        target: /docker-entrypoint-initdb.d/create_user.sh
        read_only: true
  web:
    cap_drop:
      - ALL
    container_name: bbs-web
    depends_on:
      db:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          cpus: 0.3
          memory: 256M
        reservations:
          cpus: 0.1
          memory: 128M
    environment:
      APP_ENV: production
      DB_DATABASE: ${MYSQL_DATABASE:?}
      DB_HOST: bbs-db
      DB_PASSWORD_FILE: /run/secrets/mysql_password
      DB_PORT: "3306"
      DB_USER: ${MYSQL_USER:?}
      SESSION_SECRET_FILE: /run/secrets/session_secret
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f -L -o /dev/null -s -x "" http://localhost:4567/ || exit 1
      timeout: 10s
      interval: 10s
      retries: 5
      start_period: 0s
    image: ghcr.io/shakiyam/bbs
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"
    networks:
      default: null
    ports:
      - mode: ingress
        target: 4567
        published: "4567"
        protocol: tcp
    read_only: true
    restart: unless-stopped
    secrets:
      - mysql_password
      - session_secret
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
networks:
  default:
    name: bbs-default
secrets:
  mysql_password:
    file: ./secrets/mysql_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  session_secret:
    file: ./secrets/session_secret.txt
volumes:
  db-data:
    name: bbs-db-data
