services:
  db:
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_bin
    container_name: bbs-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:?}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_USER: ${MYSQL_USER:?}
    healthcheck:
      test:
      - CMD-SHELL
      - echo 'SELECT 1' | mysql --host bbs-db --port 3306 -u ${MYSQL_USER:?} -p${MYSQL_PASSWORD:?} -s ${MYSQL_DATABASE:?} >/dev/null 2>&1
      timeout: 10s
      interval: 10s
      retries: 5
      start_period: 0s
    image: container-registry.oracle.com/mysql/community-server:8.2
    networks:
      default: null
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/mysql
      volume: {}
  web:
    container_name: bbs-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DATABASE: ${MYSQL_DATABASE:?}
      DB_HOST: bbs-db
      DB_PASSWORD: ${MYSQL_PASSWORD:?}
      DB_PORT: "3306"
      DB_USER: ${MYSQL_USER:?}
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f -o /dev/null -s http://localhost:4567/ || exit 1
      timeout: 10s
      interval: 10s
      retries: 5
      start_period: 0s
    image: ghcr.io/shakiyam/bbs
    networks:
      default: null
    ports:
    - mode: ingress
      target: 4567
      published: "4567"
      protocol: tcp
networks:
  default:
    name: bbs-default
volumes:
  db-data:
    name: bbs-db-data
