version: '3'
services:
  db:
    image: mysql
    volumes:
      - ./mysqlconf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=bbs_admin
      - MYSQL_USER=bbs
      - MYSQL_PASSWORD=bbs
      - MYSQL_DATABASE=bbs
  web:
    build:
      context: .
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    depends_on:
      - "db"
    ports:
      - "4567:4567"
    environment:
      - DB_USER=bbs
      - DB_PASSWORD=bbs
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bbs
