version: '2'
services:
  db:
    image: mysql
    volumes:
      - ./mysqlconf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=bbs_admin
      - MYSQL_USER=bbs
      - MYSQL_PASSWORD=bbs
      - MYSQL_DATABASE=bbs
  web:
    build:
      context: .
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    depends_on:
      - "db"
    ports:
      - "4567:4567"
    environment:
      - DB_ENV_MYSQL_USER=bbs
      - DB_ENV_MYSQL_PASSWORD=bbs
      - DB_ENV_MYSQL_DATABASE=bbs
      - DB_PORT_3306_TCP_ADDR=bbs_db_1
      - DB_PORT_3306_TCP_PORT=3306
