version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=bbs_admin
      - MYSQL_USER=bbs
      - MYSQL_PASSWORD=bbs
      - MYSQL_DATABASE=bbs
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default_authentication_plugin=mysql_native_password
  web:
    image: shakiyam/bbs
    depends_on:
      - "db"
    ports:
      - "4567:4567"
    environment:
      - DB_USER=bbs
      - DB_PASSWORD=bbs
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bbs
