source 'https://rubygems.org/'

gem 'capybara', '>= 3.9.0'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'ruby-mysql'
gem 'sequel'
gem 'sinatra', '>= 2.0.4'
gem 'sinatra-contrib', '>= 2.0.4'
gem 'slim'
