name: Check for updates
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  check_for_image_updates:
    name: Check for image updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run check_for_image_updates.sh
        run: ./tools/check_for_image_updates.sh "$(awk -e '/FROM/{print $2}' Dockerfile)" docker.io/ruby:alpine
  check_for_library_updates:
    name: Check for library updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run bundle lock
        run: ./tools/update_lockfile.sh -e
  check_for_new_release:
    name: Check for new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run check_for_new_release.sh
        run: |
          ./tools/check_for_new_release.sh Bootstrap twbs/bootstrap "$(grep -o 'bootstrap@[^\/]*' app.rb | awk -F'@' 'NR==1{printf "v%s", $2}')"
          ./tools/check_for_new_release.sh actions/checkout actions/checkout "$(grep -o 'actions/checkout@[^\/]*' .github/workflows/lint_and_build.yml | awk -F'@' 'NR==1{printf "%s", $2}')" '(v[0-9]+)'
          ./tools/check_for_new_release.sh docker/build-push-action docker/build-push-action "$(grep -o 'docker/build-push-action@[^\/]*' .github/workflows/lint_and_build.yml | awk -F'@' 'NR==1{printf "%s", $2}')" '(v[0-9]+)'
          ./tools/check_for_new_release.sh docker/setup-buildx-action docker/setup-buildx-action "$(grep -o 'docker/setup-buildx-action@[^\/]*' .github/workflows/lint_and_build.yml | awk -F'@' 'NR==1{printf "%s", $2}')" '(v[0-9]+)'
          ./tools/check_for_new_release.sh docker/setup-qemu-action docker/setup-qemu-action "$(grep -o 'docker/setup-qemu-action@[^\/]*' .github/workflows/lint_and_build.yml | awk -F'@' 'NR==1{printf "%s", $2}')" '(v[0-9]+)'
          ./tools/check_for_new_release.sh hadolint/hadolint-action hadolint/hadolint-action "$(grep -o 'hadolint/hadolint-action@[^\/]*' .github/workflows/lint_and_build.yml | awk -F'@' 'NR==1{printf "%s", $2}')" '(v[0-9]+)'
